version: "3.3"
services:

  postgres:
    image: postgres:12.11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
      - POSTGRES_DB=intshop
    ports:
      - '5433:5432'

    volumes:
      - ./pgdata:/var/lib/postgresql/data

  server:
    container_name: server-part
    restart: unless-stopped
    image: dmitriytuz123/server_a
    build:
      context: server
#      target: production
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

    depends_on:
      - postgres

#    network_mode: "host"

#    environment:
#      - NODE_ENV=development

#    entrypoint: ["bin/bash", "./entrypoint.sh"]

    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules

  client:
    container_name: client-part
    restart: unless-stopped
    image: dmitriytuz123/client_a
    build:
      context: client
#      target: production
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

    depends_on:
      - server


